Обновление 25 вопроса
blinky-z/ThreadsLearn pull request #2
Opened 2018-10-13 20:03 UTC by blinky-z

2018-10-13 20:31 UTC, blinky-z commented on README.MD
> -**Примитивы синхронизации** - механизмы, позволяющие обеспечить единовременно доступ только одного потока к критической области.
тест

2018-10-13 20:32 UTC, blinky-z commented on README.MD
> +**Примитивы синхронизации** - механизмы, позволяющие обеспечить единовременно доступ только одного потока к критической области, а также взаимодействие потоков.
тест2 start a review

2018-10-14 14:44 UTC, misterixis requested changes

2018-10-14 14:44 UTC, misterixis commented on README.MD
> +Существует различные алгоритмы, использующие спинлоки. Например: *алгоритцм Петерсона*, *TSL (Test and Set Lock) * (блокировка шины памяти, которая запрещает другим потокам получить доступ к памяти).
Нужно разобраться с причинно-следственной связью : что первичнее TSL, спинлоки и вот это всё

2018-10-14 14:44 UTC, misterixis commented on README.MD
> +**Монитор** - механизм, который предоставляет процедуры, взаимодействующие с критической областью.
Какой пример в `с++` есть?

2018-10-15 08:17 UTC, blinky-z commented on README.MD
> +Существует различные алгоритмы, использующие спинлоки. Например: *алгоритцм Петерсона*, *TSL (Test and Set Lock) * (блокировка шины памяти, которая запрещает другим потокам получить доступ к памяти).
Обновил

2018-10-15 08:18 UTC, blinky-z commented on README.MD
> +Существует различные алгоритмы, использующие спинлоки. Например: *алгоритцм Петерсона*, *TSL (Test and Set Lock) * (блокировка шины памяти, которая запрещает другим потокам получить доступ к памяти).
Теперь мерджу

2018-10-15 08:20 UTC, merged

2018-10-15 18:12 UTC, misterixis commented on README.MD
> +Мьютексы следует применять в ситуациях, когда необходимо ограничить количество одновременно работающих с критической областью потоков до одного (то есть единовременно с критической областью может раб
Правильно ли я понимаю, что в мьютексах всегда будет происходить переключение контекста? В отилчие от спинлока, где всегда не будет происходить переключение контекста? Почему так?

2018-10-15 18:13 UTC, misterixis commented on README.MD
> +Активное ожидание следует применять, когда есть **гарантия того, что ожидание будет недолгим**, так как недолгое простаивание стоит меньше, чем вызов планировщика и проделывание Context Switch, т.к.
Что такое недолгое? Как мне, разрабатывая программу, знать, сколько тут будет ожидание?