Реализация примитивов
blinky-z/ThreadsLearn pull request #4
Opened 2018-10-17 17:08 UTC by blinky-z

2018-10-17 18:54 UTC, misterixis requested changes

2018-10-17 18:54 UTC, misterixis commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
А язык какую команду использует? Что ты будешь делать в своём абстрактном языке?

2018-10-17 18:54 UTC, misterixis commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Откуда у нас требование к lock-free? Почему wait-free не подойдёт? Что это вообще за штуки такие? Какая из них даёт бОльшие гарантии?

2018-10-17 18:54 UTC, misterixis commented on Spinlock.h
> +    void acquire();
Слушай, понятно же, что такие вещи, как канкуренси программы нужно тестить ;)

В джаве ты бы это сделал с помощью jcstress. Тут тоже надо такое.

Надо убедится, что поведение корректное, что нет дедлково, гонок и прочего. Написание такого теста - тоже сложная задача.

2018-10-17 18:54 UTC, misterixis commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 14)
почему `14`?

2018-10-17 19:06 UTC, blinky-z commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 14)
думал что атомики в 14 появились поменял

2018-10-17 19:08 UTC, blinky-z commented on Spinlock.h
> +    void acquire();
у меня тест был но он какой то фиговый
ваще хз как правильно тестить

2018-10-17 19:08 UTC, blinky-z commented on Spinlock.h
> +    void acquire();
добавил тест но он фиговый

2018-10-17 19:10 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Lock free требуется потому что сам спинлок этого требует, он не должен блокироавться, а крутиться в цикле

2018-10-17 19:19 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
писал бы ассемблерный код наверное вручную

2018-10-17 19:20 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
или использовать команды предоставляемые процессором - XCHG

2018-10-17 19:52 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Lock-free свойство гарантирует что хотя бы один поток из всех кто вызывает lock free функцию будет добиваться прогресса (т.е. system wide прогресс)
Wait-free гарантирует что все потоки вызывающие эту функцию будут добиваться прогресса в выполнении

2018-10-17 19:53 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
когда я вызываю acquire() хотя бы 1 поток точно захватит лок, это гарантированно, acquire() никак не может быть wait-free

2018-10-17 20:48 UTC, misterixis commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
Что-то не понятно, что ты написал. Как будто, первая часть фразы пропала. Что значит "или"?

Если ты скомпилируешь код, задизасемблишь его, там будет CMPXCHG?

2018-10-17 20:50 UTC, misterixis commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Ничего не понял. Какая из гарантий более сильная? Не понял, почему понятия wait/lock-free саязаны с спинлоком.

2018-10-17 20:51 UTC, misterixis commented on Spinlock.h
> +    void acquire();
блин, ну если он фиговйый, то зачем ты его добавил. 

Не нужно заниматся pull request driven development, когда ты кидаешь код, и коллеги его подправляют. PR - это код, который ты должен быть готов отправить на реальный боевой сервер.

2018-10-17 20:53 UTC, misterixis commented on spinlock_test.cpp
> +    for (int i = 0; i < 100; i++) {
мелкие очень цифры для тестирования мнгогопоточности. Там обычно оперерируют порядками "миллион", или больше

2018-10-17 20:53 UTC, misterixis commented on spinlock_test.cpp
> +const int THREADS_NUM = 2;
Побольше тредов давай

2018-10-19 05:43 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
Нельзя сказать гарантировано что там будет, т.к. реализация зависит от архитектуры процессора

2018-10-19 06:05 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Потому что спинлок - это lock free лок, то есть хотя бы 1 поток который заблокирован на спинлоке, будет добиваться прогресса. Поэтому нам нужен atomic_flag, реализация которого полностью lock_free.

2018-10-19 06:08 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Wait free спинлок - сделать невозможно. Так как локи как раз так и требуются для того, чтобы исключать race condition, то есть единовременно должен добиваться прогресса только 1 поток, а остальные ждать

2018-10-19 06:11 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Какая из гарантий более сильная - думаю, wait free, так как лучше же многим потокам добиваться прогресса чем одному, вроде по логике так
 Но я ещё почитаю

2018-10-19 06:50 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
Но вообще я смотрел реализацию функций в либе, и там был команда preempt_disable() и preempt_enable() - это то, что использует язык

2018-10-19 06:58 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
Как язык сделает такие вещи - действительно зависит от архитектуры

2018-10-19 07:22 UTC, gravity182 commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
Две основные вещи плюсов, как реализуются в них атомарные операции - это cas операции и использование мьютекса. При чем использование какого именно способа, зависит от архитектуры.
 Если есть поддержка cas на аппаратном уровне, то да, язык заиспользует cas операции, т.к. плюсы стараются делать атомарные операции lock free, если нет поддержки cas на аппаратном уровне, то используется мьютекс

2018-10-19 07:26 UTC, gravity182 commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
Возможно есть ещё какие то способы кроме cas операций и мьютекса, но я не знаю о них

2018-10-19 15:53 UTC, misterixis commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
А как реализуется мьютекс? Ты пишешь, что он использутеся, если нет поддержки CAS на аппаратном уровне, интересно, как он сам работает?

2018-10-19 15:54 UTC, misterixis commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
подытожив, сформулируй, что такое lock free and wait free, и про то, что сильнее. И про то, где что из этого используется, и когда надо использовать lock free, а когда wait free?

2018-10-19 15:55 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
я не знаю пока как он работает, не реализовывал еще сам. завтра сделаю его и тогда отвечу

2018-10-20 22:38 UTC, misterixis requested changes

2018-10-20 22:38 UTC, misterixis commented on tests/mutex_tests.cpp
> +#define CATCH_CONFIG_MAIN
Нужны самые примитивные цесты в том числе - если один тред взял лок, другой взять не может

2018-10-20 22:46 UTC, misterixis commented on Mutex.h
> +    std::atomic_flag lock = ATOMIC_FLAG_INIT;
Давай сделаем ещё одну реализацию - на с++ до версии 11

2018-10-20 22:47 UTC, misterixis commented on Mutex.cpp
> +    while (lock.test_and_set()) {
почему у тебя именно такое условие?

2018-10-21 08:42 UTC, blinky-z commented on Mutex.cpp
> +    while (lock.test_and_set()) {
test_and_set() возвращает значение, которое было до начала операции. Если там было 0, то есть лок свободен, то значит сейчас мы смогли захватить его установив 1. Если вернуло 1, то значит лок уже захвачен каким-то другим потоком. 
 Мы знаем, что мы точно смогли захватить значение если до начала операции было 0, потоуму что это атомарная операция и чтение и установка происходят неделимо, как единая операция,то есть гарантируется то, чтодругие потоки ни читали, ни изменяли значение: 0 вернется только одному потоку (лок свободен), остальные получат 1 (лок захвачен кем-то)

2018-10-21 16:37 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
Теперь реализовав мьютекс могу сказать:
Мьютекс реализуется также с использованием cas-операций, ведь для того чтобы только 1 поток смог захватить лок, то есть атомарно прочитать и установить значение, также требуется поддержка cas-операций (test-and-set, compare-and-swap) со стороны процессора.

2018-10-21 16:40 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
При чем моя фраза 
> Две основные вещи плюсов, как реализуются в них атомарные операции - это cas операции и использование мьютекса
теперь не является правдой, так как мьютекс тоже реализован с помощью cas-операций

2018-10-21 16:56 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
значит атомарные операции при неимении cas операций будут использовать что-то другое, не мьютекс

2018-10-22 08:46 UTC, blinky-z commented on Spinlock.cpp
> +    // 1) Запретить прерывания, но у меня нет доступа к такой команде
В общем, теперь ещё раз отвечаю.
Я писал какую-то херню, если нет cas-операций, то используется мьютекс, это правда. Однако, это не тот мьютекс что в либе std <mutex>, а совсем другой, реализуемый компилятором (а не тот что прописан в стандарте C++) для того чтобы реализовать атомарные операции языка.
 То есть важно провести границу между **языком** и **компилятором**. Есть атомарные операции C++ - они должны быть так или иначе начиная с 11 плюсов. Но то как они реализованы - за это отвечает компилятор. Есть поддержка cas операций на аппаратном уровне? Отлично, компилятор генерирует lock free алгоритм. Нету поддержки cas операций? Окей, компилятор делает свой blocking примитив - мьютекс, и тут воля компилятора как он его сделает. Язык только говорит то что операция должна быть атомарной, остальное - дело компилятора.
 Если cas операции я изучил (ну как, более менее понял: Test-and-Set - это команда `XCHG` на Intel x86, а Compare - and - Swap - `lock cmpxchg`), то мьютекс точно нет смысла изучать, ибо он будет зависеть от компилятора, в отличие от аппаратных cas и test-and-set операций, которые компилятор  использует напрямую и код будет плюс минус похожий на различных компиляторах.

2018-10-22 10:32 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Так, существует non-blocking программирование
 Оно также может быть lock free, если гарантируется system-wide прогресс, и wait-free, если гарантируется прогресс каждого потока.
 То есть, существует 3 вида: non-blocking, non-blocking lock-free, non-blocking wait-free
  Все wait free алгоритмы - это lock free алгоритмы, но никакой lock free алгоритм не является wait free, потосу что Lock free алгоритмы гарантирует что если много тредов простаивают то хотя бы один будет делать работу, то есть system-wide прогресс, а wait free гарантирует и system-wide прогресс, и то, что никакой поток не будет простаивать бесполезно.
 Wait free алгоритмы нашли свое применение в системах реального времени потому что каждая операция никогда не должна занимать вечность, а всегда делать работу за конечное число шагов (верхний предел) 
 Такие алгоритмы очень сложно писать правильно, и нельзя сказать, что всегда лучше. Но wait free лучше чем lcok free

2018-10-22 14:39 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Так, существует non-blocking программирование
Оно также может быть lock free, если гарантируется system-wide прогресс, и wait-free, если гарантируется прогресс каждого потока.
То есть, существует 3 вида: non-blocking, non-blocking lock-free, non-blocking wait-free
Все wait free алгоритмы - это lock free алгоритмы, но никакой lock free алгоритм не является wait free, потосу что Lock free алгоритмы гарантирует что если много тредов простаивают то хотя бы один будет делать работу, то есть system-wide прогресс, а wait free гарантирует и system-wide прогресс, и то, что никакой поток не будет простаивать бесполезно.
Wait free алгоритмы нашли свое применение в системах реального времени потому что каждая операция никогда не должна занимать вечность, а всегда делать работу за конечное число шагов (верхний предел) 
Такие алгоритмы очень сложно писать правильно, и нельзя сказать, что всегда лучше. Но wait free всегда лучше чем lock free, так как wait free является starvation-free (потоки не простаивают в ожидании бесполезно, а делают какую то работу)

2018-10-22 14:39 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
Пример lock free алгоритма: атомарная операция fetch_add() реализованная с помощью cas операций 

Пусть несколько потоков вызвали эту функцию. 
Один поток будет крутиться в cas-цикле, и может крутиться даже бесконечно, но если этот поток не смог совершить операцию полностью (то есть операция compare and swap вернула false), то значит что какой-то другой поток смог выполнить эту операцию полностью. 
Таким образом, какой-то из потоков гарантированно на каждой итерации выполняет полезную работу, это и называется system-wide прогресс
 
Wait free алгоритм же, выполняет свою работу за конечное число шагов, не зависящее от других потоков (в то время как например, lock free функция fetch_add() зависит от других потоков)

2018-10-22 15:58 UTC, blinky-z commented on Spinlock.cpp
> +    // 2) Использовать атомарную переменную самого языка, при чем, реализация атомарной переменной должна быть lock-free,
И как противоложный пример спинлока или операции fetch_add реализовнной с помощью cas операций можно привести мьютекс:
 мьютекс - не lock free лок никогда. Пусть 1 поток захватил лок, и по середине работы с критической областью был вытеснен планировщиком, тогда никакой другой поток не сможет захватить мьютекс, пока первый не высвободит его. Очевидно, что тут не происходит даже system-wide прогресса и все потоки пытающиеся захватить мьютекс будут простаивать. Получается, что первый поток неявно заблокировал другие, а это противоречи понятию lock free

2018-11-02 22:33 UTC, merged